### ISSUE TITLE
Pokemon Modal 

### ISSUE THREAD

**Issue by williardxzd** [williardxzd/multitaskr-vue-course#5]
- Mostrar todos los detalles de cada pokemon dentro del modal (todos los atributos). Pueden usar componentes de bootstrap.
- Activar un boton de Next (dentro del modal) para cambiar al siguiente pokemon

### Extra
_Cuando le next pase del pokemon 20 la tabla no se va a actualizar solita_

- Ver la forma de recargar la tabla cuando estamos en un pokemon que se excede de la lista actual. **Ver este ejemplo de endpoint: pokemon?limit=20&offset=0**

[https://pokeapi.co/](url)

**Comment by AlejandroCamachodev** [comment]
Hola me pueden pasar el link de la reunión es que no tengo celular, por favor
